services:
  postgres:
    image: postgres:11-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: aura_dev
      POSTGRES_HOST_AUTH_METHOD: trust

  web:
    build: .
    depends_on:
      - postgres
    ports:
      - 5000:5000
      - 9229:9229 # Enables debugging later
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn dev
    environment:
      DATABASE_URL: postgres://postgres@postgres/aura_dev
      PORT: 5000
